services:
  challenge-app:
    container_name: challenge-app
    build: ./challenge-app
    ports:
      - "5000:5000"
    volumes:
      - ./challenge-app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

  ctf-dashboard:
    container_name: ctf-dashboard
    build: ./ctf-dashboard
    ports:
      - "8000:8000"
    volumes:
      - ./ctf-dashboard:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - challenge-app
